version: '3'

services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
      - user-service
      - product-service
      - order-service

  frontend:
    build: ./frontend-service
    ports:
      - "8501:8501"
    environment:
      - PORT=8501

  user-service:
    build: ./user-service
    ports:
      - "8001:8001"

  product-service:
    build: ./product-service
    ports:
      - "8002:8002"

  order-service:
    build: ./order-service
    ports:
      - "8003:8003" 